//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_JaxWS.SR1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="SR1.BanqueService")]
    public interface BanqueService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService_JaxWS.SR1.getCompteResponse getCompte(WebService_JaxWS.SR1.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/getCompteRequest", ReplyAction="http://ws/BanqueService/getCompteResponse")]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.getCompteResponse> getCompteAsync(WebService_JaxWS.SR1.getCompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/ConversionEuroToDHRequest", ReplyAction="http://ws/BanqueService/ConversionEuroToDHResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService_JaxWS.SR1.ConversionEuroToDHResponse ConversionEuroToDH(WebService_JaxWS.SR1.ConversionEuroToDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/ConversionEuroToDHRequest", ReplyAction="http://ws/BanqueService/ConversionEuroToDHResponse")]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.ConversionEuroToDHResponse> ConversionEuroToDHAsync(WebService_JaxWS.SR1.ConversionEuroToDHRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/compteListRequest", ReplyAction="http://ws/BanqueService/compteListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService_JaxWS.SR1.compteListResponse compteList(WebService_JaxWS.SR1.compteListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BanqueService/compteListRequest", ReplyAction="http://ws/BanqueService/compteListResponse")]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.compteListResponse> compteListAsync(WebService_JaxWS.SR1.compteListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private bool codeFieldSpecified;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        private double montantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("codeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("dateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified {
            get {
                return this.dateCreationFieldSpecified;
            }
            set {
                this.dateCreationFieldSpecified = value;
                this.RaisePropertyChanged("dateCreationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double montant {
            get {
                return this.montantField;
            }
            set {
                this.montantField = value;
                this.RaisePropertyChanged("montant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(long code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebService_JaxWS.SR1.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(WebService_JaxWS.SR1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDH", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEuroToDHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public ConversionEuroToDHRequest() {
        }
        
        public ConversionEuroToDHRequest(double montant) {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDHResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ConversionEuroToDHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEuroToDHResponse() {
        }
        
        public ConversionEuroToDHResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="compteList", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class compteListRequest {
        
        public compteListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="compteListResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class compteListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebService_JaxWS.SR1.compte[] @return;
        
        public compteListResponse() {
        }
        
        public compteListResponse(WebService_JaxWS.SR1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueServiceChannel : WebService_JaxWS.SR1.BanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueServiceClient : System.ServiceModel.ClientBase<WebService_JaxWS.SR1.BanqueService>, WebService_JaxWS.SR1.BanqueService {
        
        public BanqueServiceClient() {
        }
        
        public BanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_JaxWS.SR1.getCompteResponse WebService_JaxWS.SR1.BanqueService.getCompte(WebService_JaxWS.SR1.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public WebService_JaxWS.SR1.compte getCompte(long code) {
            WebService_JaxWS.SR1.getCompteRequest inValue = new WebService_JaxWS.SR1.getCompteRequest();
            inValue.code = code;
            WebService_JaxWS.SR1.getCompteResponse retVal = ((WebService_JaxWS.SR1.BanqueService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.getCompteResponse> WebService_JaxWS.SR1.BanqueService.getCompteAsync(WebService_JaxWS.SR1.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_JaxWS.SR1.getCompteResponse> getCompteAsync(long code) {
            WebService_JaxWS.SR1.getCompteRequest inValue = new WebService_JaxWS.SR1.getCompteRequest();
            inValue.code = code;
            return ((WebService_JaxWS.SR1.BanqueService)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_JaxWS.SR1.ConversionEuroToDHResponse WebService_JaxWS.SR1.BanqueService.ConversionEuroToDH(WebService_JaxWS.SR1.ConversionEuroToDHRequest request) {
            return base.Channel.ConversionEuroToDH(request);
        }
        
        public double ConversionEuroToDH(double montant) {
            WebService_JaxWS.SR1.ConversionEuroToDHRequest inValue = new WebService_JaxWS.SR1.ConversionEuroToDHRequest();
            inValue.montant = montant;
            WebService_JaxWS.SR1.ConversionEuroToDHResponse retVal = ((WebService_JaxWS.SR1.BanqueService)(this)).ConversionEuroToDH(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.ConversionEuroToDHResponse> WebService_JaxWS.SR1.BanqueService.ConversionEuroToDHAsync(WebService_JaxWS.SR1.ConversionEuroToDHRequest request) {
            return base.Channel.ConversionEuroToDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_JaxWS.SR1.ConversionEuroToDHResponse> ConversionEuroToDHAsync(double montant) {
            WebService_JaxWS.SR1.ConversionEuroToDHRequest inValue = new WebService_JaxWS.SR1.ConversionEuroToDHRequest();
            inValue.montant = montant;
            return ((WebService_JaxWS.SR1.BanqueService)(this)).ConversionEuroToDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_JaxWS.SR1.compteListResponse WebService_JaxWS.SR1.BanqueService.compteList(WebService_JaxWS.SR1.compteListRequest request) {
            return base.Channel.compteList(request);
        }
        
        public WebService_JaxWS.SR1.compte[] compteList() {
            WebService_JaxWS.SR1.compteListRequest inValue = new WebService_JaxWS.SR1.compteListRequest();
            WebService_JaxWS.SR1.compteListResponse retVal = ((WebService_JaxWS.SR1.BanqueService)(this)).compteList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_JaxWS.SR1.compteListResponse> WebService_JaxWS.SR1.BanqueService.compteListAsync(WebService_JaxWS.SR1.compteListRequest request) {
            return base.Channel.compteListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_JaxWS.SR1.compteListResponse> compteListAsync() {
            WebService_JaxWS.SR1.compteListRequest inValue = new WebService_JaxWS.SR1.compteListRequest();
            return ((WebService_JaxWS.SR1.BanqueService)(this)).compteListAsync(inValue);
        }
    }
}
